### ISSUE TITLE
TinyEXR breaks when compiled with MinGW and linked with -flto and -static

### ISSUE THREAD

**Issue by akien-mga** [syoyo/tinyexr#105]
Sorry for the obscure bug report, but this arises from a crash we're getting in Godot Engine: godotengine/godot#24641. It appears to be a GCC / MinGW bug, so not necessarily something that you can/should fix in TinyEXR, but I figured I'd document it here nevertheless.

**Issue description:**
When compiling TinyEXR with MinGW (`x86_64-w64-mingw32-g++ (GCC) 8.2.0 20180726 (Fedora MinGW 8.2.0-3.fc29)`), and linking with `-flto -static`, the library appears to be broken.

This can be reproduced with `test_tinyexr`:
```
$ x86_64-w64-mingw32-g++ -flto -o test_tinyexr test_tinyexr.cc -flto -static
$ cp /usr/x86_64-w64-mingw32/sys-root/mingw/bin/{libgcc_s_seh-1.dll,libstdc++-6.dll,libwinpthread-1.dll} .
$ wine test_tinyexr.exe asakusa.exr
000b:fixme:winediag:start_process Wine Staging 4.0 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
Load EXR err: "compression" attribute not found in the header.
"channels" attribute not found in the header.
"lineOrder" attribute not found in the header.
"displayWindow" attribute not found in the header.
"dataWindow" attribute not found in the header or invalid.
"pixelAspectRatio" attribute not found in the header.
"screenWindowWidth" attribute not found in the header.
"screenWindowCenter" attribute not found in the header.
(code -8)
$ ls -l output.exr
ls: cannot access 'output.exr': No such file or directory
```

If either `-flto` or `-static` is removed, everything works fine:
```
$ x86_64-w64-mingw32-g++ -flto -o test_tinyexr test_tinyexr.cc -flto
$ wine test_tinyexr.exe asakusa.exr 
000b:fixme:winediag:start_process Wine Staging 4.0 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
$ ls -l output.exr
-rw-r--r-- 1 akien akien 1186276 Feb 10 16:54 output.exr
```

**Comment by syoyo** [comment]
I got seg fault with `-flto -static` in Windows native MinGW 64 + gcc 5.3.0 envrionment.

As far as I know, `-static` is problematic for MinGW environment(STL, SEH runtime, etc..). 

For a while, it is recommended not to use `-flto` and `-static`

**Comment by lu-zero** [comment]
You should probably try with clang to pin the problem to either the compiler or the linker

**Comment by syoyo** [comment]
> You should probably try with clang to pin the problem to either the compiler or the linker

Here is some result on clang compiler(tested on x86-64 + Windows 10 64bit).

* prebuilt LLVM/clang 7.0.1 http://releases.llvm.org/download.html#7.0.1 + VS2017 : NG(linker error. invalid or corrupt file)
  * but adding `-fuse-ld=lld` works https://lld.llvm.org/
* mingw(msys2 packman) llvm 5.0.0 : NG
* llvm-mingw(https://github.com/mstorsjo/llvm-mingw) : OK

For llvm-mingw build, non-static build fails to find `api-ms-win-crt-locale-l1-1-0.dll` 

So, the problem may be the linker.

So, if you want to build Godot/TinyEXR with lto + static, using llvm-mingw or LLVM/clang + LLD would be  a solution so far > @akien-mga

**Comment by akien-mga** [comment]
Thanks for investigating, it seems like you're right in your analysis that it seems to be linker related.

GCC bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81879
Binutils bug report: https://sourceware.org/bugzilla/show_bug.cgi?id=24267

**Comment by syoyo** [comment]
Close since this is a gcc(ld)'s bug: https://github.com/godotengine/godot/issues/24641#issuecomment-468258598
