### ISSUE TITLE
Error in Deep Image Sample

### ISSUE THREAD

**Issue by abigos** [syoyo/tinyexr#118]
I think there's a small logic bug in the deep view example. When iterating over the input image the x dimension is short by 1 pixel, resulting in fewer points than expected and in addition the attributes of the points suffer from an off-by-one error.

I believe this is due to a misunderstanding of how the offset table works.  An index into the offset table at x seems to represent the start of the samples for the *next* x value.  In other words, the start of samples for x=0 on a scanline is implicitly 0 and the value of the offset[0] actually represents the location of the first sample for x=1.

I think changing the sample code along the lines as shown below would fix the problem - however I'm not able to run the OpenGL sample so please confirm.
```c
for (int y = 0; y < gDeepImage.height; y++) {
	float py = 2.0f * ((gDeepImage.height - y - 1) / (float)gDeepImage.height) - 1.0f; // upside down?
	int s_start = 0; // First pixel data starts at 0
	for (int x = 0; x < gDeepImage.width; x++) {
		float px = 2.0f * (x / (float)gDeepImage.width) - 1.0f;     
		int s_end = gDeepImage.offset_table[y][x]; // Start of next data
		for (int s = s_start; s < s_end; s++) {
			float pz = -gDeepImage.image[depthChan][y][s];
			.... 
			<snip> 
			....         
		}
		s_start = s_end;  
	}
}
```

**Comment by syoyo** [comment]
Thanks! You should be right.
 
I've compiled `deepview` with your fix and it looks working well. I'll do more tests and see if it goes well.

**Comment by syoyo** [comment]
I have pushed possible fix: https://github.com/syoyo/tinyexr/commit/ba81e4a5bb6f95f9650d97ab5910876043d809e4

@abigos Please review this fix work well.

**Comment by abigos** [comment]
Looks good, thank you. 

One minor point. The comment on this line: `int s_start = 0; //gDeepImage.offset_table[y][x];` is misleading.  The code doesn't do anything with  `gDeepImage.offset_table[y][x];` - the zero represents the implicit start of the data and `x` is not defined that this time.  My comment, above, is more accurate :-)

**Comment by syoyo** [comment]
Thanks! 

> One minor point

Fixed > https://github.com/syoyo/tinyexr/commit/939f5d743533a3cc22a296e211c4e2407ee4113a
