### ISSUE TITLE
build error on 32bit platforms (size_t) 

### ISSUE THREAD

**Issue by ziocleto** [syoyo/tinyexr#122]
Enabling warnings as errors on 32bit platforms (IE emscripten) generates this warning:

```
tinyexr.h:10911:50: error: result of comparison of constant 274877906944 with expression of type 'size_t' (aka 'unsigned long') is always false [-Werror,-Wtautological-constant-out-of-range-compare]
    if ((total_data_len == 0) || (total_data_len >= 0x4000000000)) {
                                  ~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
```

So I guess 0x4000000000 is just a magic number? Shall we check against size_t middle range instead ? 

Cheers,
Dado.

**Comment by syoyo** [comment]
As commented in the source code, this magic number is for work around for ASAN : https://github.com/syoyo/tinyexr/issues/107

I haven't been tested tinyexr on 32bit so didn't realized this issue.

You can simply remove this `total_data_len  >= 0x4000000000` conditionals on 32bit, then it should work.

**Comment by ziocleto** [comment]
Thanks for your reply, can I suggest a possible fix/PR? 
(If you are targeting c++11 onward we might can have some constexpr conditionals also)

```
    const bool magic_total_allowed_size_check = sizeof(void*) == 8 ? (total_data_len >= 0x4000000000) : false;
    if ((total_data_len == 0) || magic_total_allowed_size_check ) {

```

This builds well on 32bit including emscripten.

Cheers,
Dado.

**Comment by syoyo** [comment]
Thanks! that's perfect! PR is much appreciated.

**Comment by ziocleto** [comment]
Excellent all tests passed on the PR, have a nice day!

**Comment by syoyo** [comment]
Thanks! > PR https://github.com/syoyo/tinyexr/pull/123

So this issue is ready to close
