### ISSUE TITLE
UTF8 Support

### ISSUE THREAD

**Issue by Theverat** [syoyo/tinyexr#130]
Hi,

you might want to use a wrapper for `fopen` similar to the one stb_image uses: https://github.com/nothings/stb/blob/f67165c2bb2af3060ecae7d20d6f731173485ad0/stb_image.h#L1193
This would make it possible to load files with non-latin characters in the filepath on Windows.

Thanks for writing this library!
Best,
Simon

**Comment by syoyo** [comment]
You may also need to consider MinGW codepath:

https://github.com/syoyo/tinygltf/issues/221

PR is always welcome!

**Comment by syoyo** [comment]
Added UTF-8 filename support for Windows in `utf8` branch and also merged it to `master` branch.
Latest commit is here:
 
 https://github.com/syoyo/tinyexr/commit/9d89b54fd996ce57bc41567e5825cb86d5992182
