### ISSUE TITLE
New Layers API reads incorrect channels for single channel layers

### ISSUE THREAD

**Issue by reiner-dolp** [syoyo/tinyexr#132]
I have an exr file exported from mitsuba, with the following structure: rgb layer, r layer. When I try to load the single channel layer, tinyexr incorrectly loads the first channel of the first layer.

**Why it happens**

[Line 11604](https://github.com/syoyo/tinyexr/blob/master/tinyexr.h#L11604) incorrectly reads the first channel instead of `chIdx`. Therefore, the proposed patch is:

Substitute:

```
const float val = reinterpret_cast<float**>(exr_image.images)[0][i];
```
with:
```
const float val = reinterpret_cast<float**>(exr_image.images)[chIdx][i];
```

**Comment by syoyo** [comment]
Thanks for the report! Fixed!
