### ISSUE TITLE
Load miss the layer which name is without .RGB or .XYZ suffix

### ISSUE THREAD

**Issue by Ly890608** [syoyo/tinyexr#137]
The layer name seems to have a .RGB or .XYZ suffix.
in my case,  the layer name is 'noiseLevel', it can not be loaded.
and i rename the layer 'noiseLevel' to 'noiseLevel.RGB'. it 's OK.

**Comment by syoyo** [comment]
If you use uncommon layer names, you need manually load image data using `LoadEXRImageFromFile`  https://github.com/syoyo/tinyexr#loading-singlepart-exr-from-a-file
