### ISSUE TITLE
LineOrder inverted

### ISSUE THREAD

**Issue by andrewfb** [syoyo/tinyexr#14]
If I'm not mistaken, the code for handling lineOrder is correct but exactly inverted. [Per this comment](https://github.com/syoyo/tinyexr/blob/82f895910bf967aa84c3e608b2404ac448e1596f/tinyexr.cc#L7378) the code is written with the assumption that `lineOrder=1` implies increasing line order. However I believe this should be `0`, not `1`. I also confirmed this with the [file layout spec](http://www.openexr.com/openexrfilelayout.pdf) - sorry can't deep-link that but lineOrder is defined on page 15. If if this is true, I'd be happy to submit a PR that flips it.

**Comment by syoyo** [comment]
Hello Andrew,

Oops, you are right. The output image from tinyexr looks correctly ordered, thus simply the comment is wrong.

And, PR is always welcome!

**Comment by andrewfb** [comment]
If I'm not misinterpreting it, `ASCENDING_Y`, which is 0, implies that the scanlines are stored top-to-bottom, correct? So I believe a [line like this](https://github.com/syoyo/tinyexr/blob/51ab09c9b74a455c1fbb8d2bed80a7c9ff062c2a/tinyexr.cc#L7587) is reversed. As an aside, when I merged the commit that added the lineOrder parameter, all of my images flipped upside down. Am I just misreading all of this?

**Comment by syoyo** [comment]
> Am I just misreading all of this?

You looks correct.

extcat is a good tool to test result with OpenEXR,

https://github.com/syoyo/tinyexr/blob/51ab09c9b74a455c1fbb8d2bed80a7c9ff062c2a/test/exrcat/exrcat.cpp

And interestingly, when I run this with recent `tinyexr` code, the output become different(i.e. lineOrdering flipped)… although it reported identical result before. @mmp do you have any idea?

**Comment by syoyo** [comment]
It looks like the inconsistency has been introduced here

https://github.com/syoyo/tinyexr/commit/8c7a86564d843e512bd1235be50f93319facdaec

So is it OK to invert lineOrder value, @mmp?

**Comment by mmp** [comment]
Oops, sorry about that. That fix looks good to me.

**Comment by syoyo** [comment]
> Oops, sorry about that. That fix looks good to me.
