### ISSUE TITLE
Performance issues when threading (either custom or openmp)...

### ISSUE THREAD

**Issue by jeffatrad** [syoyo/tinyexr#143]
On Windows, the large temporary allocations for the tmpBuf buffer in DecompressZip, and the outBuf buffer in DecodePixelData trigger the allocator to fallback to an OS large allocation.  For 4K images, constantly reallocating these two large buffers takes around 15% of the total decompression time.

It's fairly easy to fix by demand allocating them into a structure that is maintained across calls to DecodePixelData().

It's not a huge code delta and the win is pretty large (on Windows - haven't tested Linux, but I assume similar).

**Comment by syoyo** [comment]
It is known that standard allocator in STL(on all OSes) take a lock so it is problematic on threading environment.
Could you send a PR?

**Comment by jeffatrad** [comment]
Sure, we're just very diverged.  We have SSE2 code paths in there for the hot paths, we have a switch to build without STL, we have the job system support, etc.  All of this is on switches (TINY_EXR_USE_SSE2, TINYEXR_NO_STL, TINYEXR_USE), though.

But I can send later today and you can pick and choose what to move over.

**Comment by syoyo** [comment]
Good! PR per feature is appreciated 🙏

**Comment by syoyo** [comment]
Close the issue since there is no PR submitted
