### ISSUE TITLE
experimental/js: node test.js fails

### ISSUE THREAD

**Issue by gernotziegler** [syoyo/tinyexr#145]
**Describe the issue**
In Linux (Gentoo), node test.js, as described in experimental/js/README.md, seems to fail with emscripten-latest. 
(the webpage test works, though) 

**To Reproduce**
1. Download and install emsdk 
2. go to /experimental/js
3. Run ./compile_to_js.sh
4. Run node test.js 

Output (below a dump of the javascript, apparently )

TypeError: tinyexr.EXRLoader is not a constructor
    at Object.<anonymous> (/root/git/tinyexr/experimental/js/test.js:7:16)

**Expected behavior**
(dont know expected result)

**Environment**
 - OS: Linux Gentoo  default/linux/amd64/17.1/desktop
 - Compiler: em++ emcc (Emscripten gcc/clang-like replacement) 2.0.1 (4ee902fd6963233f6be8b818eebd529ae406221e)

**Comment by syoyo** [comment]
JS binding is experimental and not maintained recently.
