### ISSUE TITLE
experimental/js: WASM compilation cannot be loaded

### ISSUE THREAD

**Issue by gernotziegler** [syoyo/tinyexr#146]
**Describe the issue**
The webpage index.html in experimental/js complains that the generated WASM output file cannot be loaded. 

**To Reproduce**
1. Compile /experimental/js with latest emscripten by running ./compile_to_js.sh
2. Bind directory to webserver (in my case, I uploaded it to my server www.geofront.eu) 
3. Open hosted URL - https://www.geofront.eu/exrjs/

wasm streaming compile failed: TypeError: Response has unsupported MIME type tinyexr.js:1:13661
falling back to ArrayBuffer instantiation

**Expected behavior**
WASM loads without complaints

**Environment**
- OS: Linux Gentoo 
- Firefox: 68.12.0esr (64-bit)  (based on Gentoo package firefox-bin) 
 - Compiler: emcc (Emscripten gcc/clang-like replacement) 2.0.1 (4ee902fd6963233f6be8b818eebd529ae406221e)
(Let me know if you need more background info :-) )

**Comment by syoyo** [comment]
JS binding is experimental and not maintained
