### ISSUE TITLE
New official release

### ISSUE THREAD

**Issue by intelligide** [syoyo/tinyexr#149]
It has been 4 years since the last release (0.9.5). Is there a plan for a new release ?

Im trying to package tinyexr for Conan (See conan-io/conan-center-index#2830) and it would be nice if I could use a stable version.

**Comment by syoyo** [comment]
Although it is not explicitly versioned, `master` branch is always a stable release.

I don't recommend to use Conan, since TinyEXR is a header-only library.

**Comment by Croydon** [comment]
@syoyo Will you ever do another release or should master be now always considered the best choice?

**Comment by syoyo** [comment]
@Croydon You can consider `master` is the best choice. And I have tagged `v1.0.0` to recent `master`  https://github.com/syoyo/tinyexr/tree/v1.0.0

**Comment by Croydon** [comment]
@syoyo Thank you!
