### ISSUE TITLE
handling of pixel_types is inconsistent for loading/saving with half

### ISSUE THREAD

**Issue by mmp** [syoyo/tinyexr#15]
With the LoadMultiChannelEXR* functions, the data returned in ExrImage::images is in the same format as is stored in ExrImage::pixel_types (e.g. half data is returned in half format, etc.)

However, for the Save* functions, if the caller sets pixel_types to TINYEXR_PIXELTYPE_HALF, the pixels must be provided as float32 values and tinyexr does the conversion.

This seems inconsistent. I'd argue that the most consistent thing would be to always return half data directly if the file was stored in half, maybe also providing half->float conversion functions for convenience.

(This is obviously closely related to issue #11.)

**Comment by mmp** [comment]
I'm an idiot, float data is both returned and expected for Load/Save.

**Comment by syoyo** [comment]
Good point anyway. At this time tinyexr converts half <-> float internally. This is convienient for most people who want just use tinyexr to read/store .EXR image. But it would be nice(especially in Load function) that tinexr doesn't do half -> float conversion for the use of fp16 texture on GPU as pointed out by #11 @andrewfb .

I haven't yet realised to find a good API interface for that. Adding 'halfToFloat' flag to Load function would be one of the solution. Do you have any idea?

**Comment by richardeakin** [comment]
We were thinking it would be nice if the `ExrImage` struct contained an additional array like `internal_pixel_types`, which represented the data type used to store the pixels in the file, while `pixel_types` could define what type of data is pointed to at `unsigned char **images`.

**Comment by syoyo** [comment]
Thanks @richardeakin !

> We were thinking it would be nice if the ExrImage struct contained an additional array like internal_pixel_types
