### ISSUE TITLE
Warnings when compiling with VS2019 and W3 (32 bit)

### ISSUE THREAD

**Issue by delhoume** [syoyo/tinyexr#171]
On windows with /W3 flags I have 

 `cl /EHsc /W3 /I. /I..\..\stb  simpleload.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.32.31329 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

simpleload.cpp
.\tinyexr.h(2506): warning C4018: '<': signed/unsigned mismatch
.\tinyexr.h(2763): warning C4018: '<': signed/unsigned mismatch
.\tinyexr.h(7345): warning C4244: 'argument': conversion from 'tinyexr::tinyexr_uint64' to 'size_t', possible loss of data
.\tinyexr.h(7398): warning C4244: 'return': conversion from 'tinyexr::tinyexr_uint64' to 'size_t', possible loss of data
.\tinyexr.h(8681): warning C4018: '>': signed/unsigned mismatch`

**Comment by syoyo** [comment]
PR of suppressing warnings much appreciated.

**Comment by delhoume** [comment]
I will make one. meanwhile here is my sample:

`#define TINYEXR_USE_MINIZ 0
#define TINYEXR_USE_STB_ZLIB 1
#define TINYEXR_IMPLEMENTATION
#include <tinyexr.h>

#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb_image_write.h>

#include <iostream>

int 
main(int argc, char* argv[]) {
	int width, height;
	float* image;
    const char* error;

	int ret = LoadEXR(&image, &width, &height, argv[1], &error);
	if (ret == TINYEXR_SUCCESS) {
 	    free(image);
    } else {
        std::cout << error << std::endl;
        FreeEXRErrorMessage(error);
    }
    return 0;
}`

Note that I have this error also : \tinyexr.h(1332): error C2065: 'ret': undeclared identifier
this is trivial to correct, just rename r to ret in defined portion for TINYEXR_USE_STB_ZLIB

**Comment by syoyo** [comment]
> Note that I have this error also : \tinyexr.h(1332): error C2065: 'ret': undeclared identifier

👀 https://github.com/syoyo/tinyexr/blob/bb37f77368fe458db234728b68098e5c0cac16d0/tinyexr.h#L1332

It'd be better to report an error instead of assertion, by modifying `void CompressZip` to  `bool CompressZip`.

**Comment by delhoume** [comment]
I made a PR, please check and make changes you find usefull

**Comment by syoyo** [comment]
Closed via https://github.com/syoyo/tinyexr/pull/172
