### ISSUE TITLE
embedding tinyexr to Piccante

### ISSUE THREAD

**Issue by banterle** [syoyo/tinyexr#20]
I would like to embed tinyexr to Piccante as EXR library of choice.

**Comment by syoyo** [comment]
tinyexr is licensed under BSD license

**Comment by banterle** [comment]
that's very nice; I will start to embed it in the develop branch and have it in the next release! Thanks for such a nice library!

**Comment by syoyo** [comment]
For what its' worth, I made TinyEXR single header file only. https://github.com/syoyo/tinyexr/commit/5fd4e0b28f37e39edc22feffe4031099283e8f61

**Comment by banterle** [comment]
that's super good!
