### ISSUE TITLE
Problems decoding several OpenEXR reference files

### ISSUE THREAD

**Issue by tobybear** [syoyo/tinyexr#203]
I have problems with several files from the OpenEXR test images folder, for example with this one:
https://raw.githubusercontent.com/AcademySoftwareFoundation/openexr-images/main/v2/LeftView/Balls.exr
(single part, ZIPS compression).
On trying to load it, I get "Load EXR err: Invalid/Corrupted data found when decoding pixels."
Using other (OpenEXR based) loaders, the files work fine.
Any idea what could be the issue?

**Comment by syoyo** [comment]
You can set a watchpoint on `invalid_data` in a debugger then you'll find something.

https://github.com/syoyo/tinyexr/blob/6c8742cc8145c8f629698cd8248900990946d6b1/tinyexr.h#L5398

As you can see, current implementation lacks detailed error reports.  Contribution of better error reporting is much appreciated!

**Comment by syoyo** [comment]
Balls.exr has deepscanline format, 

https://openexr.com/en/latest/test_images/index.html#stereo-images

which is not supported in current tinyexr.

Filed as another issue: https://github.com/syoyo/tinyexr/issues/211
