### ISSUE TITLE
Clang compiler settings break clang-cl compilation on windows

### ISSUE THREAD

**Issue by fknfilewalker** [syoyo/tinyexr#207]
**Environment**
 - OS: Windows
 - Compiler  clang-cl

**Comment by syoyo** [comment]
You should describe details

**Comment by fknfilewalker** [comment]
Oh yes sorry

In the cmake the following code gets activated when the compiler that is used is clang.
https://github.com/syoyo/tinyexr/blob/2a5ea89728ed3baac746a75b806a97f402e197c2/CMakeLists.txt#L46

The problem here is that there are some warnings that get turned into errors now on the windows side making the code not compile with clang-cl.

So either we fix the code in `tinyexr.cc` so that these warnings/errors for windows get resolved or we deactivate these compiler flags for clang-cl.

**Comment by syoyo** [comment]
Ah, o=it is needed to wrap it with MSVC to detect clang-cl.

```
if (MSVC) 
  if (CMAKE_CXX_COMPILER_ID SQTEQUAL "Clang")
    // clang-cl
  else() 
    // cl.exe
  endif()
endif ()
```

You can contribute! PR is much appreciated.
