### ISSUE TITLE
About tinyexr.js

### ISSUE THREAD

**Issue by stephane-lb** [syoyo/tinyexr#25]
Hi,

I discovered your project to have a tinier.js, my question are really basics, is it working and do you have any example that you could share ?

Many thanks

Stephane

**Comment by syoyo** [comment]
tinyexr.js is experimental. At this time you can't expect too much for it. PR is always welcome.

**Comment by syoyo** [comment]
Now its working: https://github.com/syoyo/tinyexr/issues/43
