### ISSUE TITLE
warning C4334 on VS2015 with update 2

### ISSUE THREAD

**Issue by baldurk** [syoyo/tinyexr#26]
Hi, when buliding tinyexr (e.g. via test.cc) on VS2015 update 2, you get the following warnings:

```
1>c:\projects\tinyexr\tinyexr.h(2295): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
1>c:\projects\tinyexr\tinyexr.h(8013): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
```

They're both shifting 1 into a particular bit, so you could fix the warning by explicitly shifting `1ULL` so it's 64-bit in the first place.

Or it could be added to the suppressed warnings with `#pragma warning(disable : 4334)`. The only downside of this option is that the first warning on line 2295 is in the miniz code above the existing warning disables.

**Comment by syoyo** [comment]
You can send a PR
