### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by hkubo1983** [syoyo/tinyexr#28]
Hello syoyo-san,

Thanks for providing an awesome IO library,
but a memory leak is detected in my environment (Visual C++ 2015).

The leak is detected inside "LoadEXR()" function.
Probably just missing "FreeEXRImage" function at the end of "LoadEXR()" function.
So, my idea is, just insert:
**tinyexr.h:10446 FreeEXRImage(&exr_image);**

Thanks!

**Comment by syoyo** [comment]
Thanks for reporting! Fixed.
