### ISSUE TITLE
unused variable warning

### ISSUE THREAD

**Issue by oliviersoares** [syoyo/tinyexr#33]
Hi Syoyo,

Tiny issue: when compiling with "-Wall" flag, we get this warning:
```
tinyexr.h:9300:10: warning: unused variable 'ret' [-Wunused-variable]
```

Could you add this:
```
(void)ret;
```
line 9305, after the assert to avoid the warning?

Thanks.
-oliv

**Comment by syoyo** [comment]
Thanks for the report! Fixed.
