### ISSUE TITLE
thread safety?

### ISSUE THREAD

**Issue by fbriggs** [syoyo/tinyexr#38]
Thanks for making this! Love the single header approach.

I am trying to save RGBD data from opencv mats to file, using SaveEXR. It works fine, unless I call my function in multiple threads, in which case it crashes with "Illegal instruction: 4". I am running it on OS X. I have a little wrapper around SaveEXR, listed below-

```
void writeEXR4ChannelRGBD(
    const Mat& imageBGR,
    const Mat& depthmap,
    const string& filename,
    const float gamma,
    const float unitScale) {

  // scale depthmap to same size as image (it might be smaller)
  Mat resizeDepth;
  resize(
    depthmap,
    resizeDepth,
    imageBGR.size(),
    0, 0,
    CV_INTER_LINEAR);

  // pack RGB and D together. apply gamma correction to RGB, and unit conversion
  // to D.
  Mat rgbd;
  cvtColor(imageBGR, rgbd, CV_BGR2RGBA);
  for (int y = 0; y < rgbd.rows; ++y) {
    for (int x = 0; x < rgbd.cols; ++x) {
      rgbd.at<Vec4f>(y, x)[0] = pow(rgbd.at<Vec4f>(y, x)[0], gamma);
      rgbd.at<Vec4f>(y, x)[1] = pow(rgbd.at<Vec4f>(y, x)[1], gamma);
      rgbd.at<Vec4f>(y, x)[2] = pow(rgbd.at<Vec4f>(y, x)[2], gamma);
      rgbd.at<Vec4f>(y, x)[3] = resizeDepth.at<float>(y, x) * unitScale;
    }
  }

  static const int kChannels = 4;
  if (0 != SaveEXR(
      (const float*)rgbd.data,
      rgbd.cols,
      rgbd.rows,
      kChannels,
      filename.c_str())) {
    throw VrCamException("failed to write EXR: " + filename);
  }
}
```

**Comment by fbriggs** [comment]
so the issue is that If I call this function in a single thread it is OK, but multiple concurrent crashes. this could be a bug in my code somewhere, or it could be in SaveEXR. I'm not sure at this point. will update if I find out anything interesting

**Comment by syoyo** [comment]
I have encountered similar seg fault problem on macOS 10.11 + multi-thread program in the past. macOS 10.12 looks works fine(also on Linux and Windows works fine) 

There may be still non-thread safe code in SaveEXR, or some illegal use case of macOS's STL libs.

I may try TSAN https://clang.llvm.org/docs/ThreadSanitizer.html for finding thread problem(even though it only works on Linux environment).

**Comment by syoyo** [comment]
Also, I appreciate you posts minimum reproducable code(without OpenCV code would be nice)

**Comment by syoyo** [comment]
I don't encounter segfault anymore with macOS 10.12+

Please reopen an issue with reproducable code if you still have an issue.
