### ISSUE TITLE
Issue compiling with OpenMP with last change

### ISSUE THREAD

**Issue by oliviersoares** [syoyo/tinyexr#42]
Hi,

You last change:
https://github.com/syoyo/tinyexr/commit/13c7cfd070b6c691ba50b5c58027b9cfd801d381

introduces a regression which prevents me from compiling tinyexr projects when using OpenMP (cflag "-fopenmp").

You can repro the issue if you change your Makefile and add "-fopenmp" to CXXFLAGS and recompile.

You should get the following compile error:
tinyexr.h: In function ‘int tinyexr::DecodeChunk(EXRImage*, const EXRHeader*, const std::vector<long long unsigned int>&, const unsigned char*)’:
tinyexr.h:10459:9: error: break statement used with OpenMP for loop
         break;

According to the OpenMP doc, you can't use a "break" statement inside a for loop:
<<<
The for-loop must be a structured block, and in addition, its execution must not be terminated by a break statement.
>>>

Here's some info regarding this issue:
https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/304882

Thanks a lot!
olivier

**Comment by syoyo** [comment]
Thanks! Now removed `break` and confirmed OpenMP build become OK.
