### ISSUE TITLE
Miniz/zlib

### ISSUE THREAD

**Issue by john-chapman** [syoyo/tinyexr#46]
I am already using Miniz in my project; I therefore want to do this to disable the embedded version of Miniz:
```
#define TINYEXR_IMPLEMENTATION
#define TINYEXR_USE_MINIZ 0
#include "miniz.h"
#include "tinyexr.h"
```
However, tinyexr.h wants to include zlib.h:
```
#if TINYEXR_USE_MINIZ
#else
#include "zlib.h"
#endif
```
My opinion is that it would be preferable to remove this dependency and leave it up to the user to include their zlib-compatible header (either zlib.h or miniz.h, as in my case) _before_ including tinyexr.h.

**Comment by syoyo** [comment]
> My opinion is that it would be preferable to remove this dependency and leave it up to the user to include their zlib-compatible header (either zlib.h or miniz.h, as in my case) before including tinyexr.h.

This looks good so I made a change in the recent commit.

Thank you for reporting an issue!

**Comment by zigguratvertigo** [comment]
I've also made similar changes on my side, where we have other modules in our code relying on miniz already.

We've basically removed lines 475 to 6909, and now only rely on:

```
#if TINYEXR_USE_MINIZ
#include <miniz/miniz.h>
#else
#include "zlib.h"
#endif
```

**Comment by syoyo** [comment]
> we have other modules in our code relying on miniz already.

Okay, I'm considering to introduce `TINYEXR_USE_EXTERNAL_MINIZ` define, which assumes user code already includes `miniz` header.

**Comment by john-chapman** [comment]
I don't see that it's necessary to add a new define, it's simpler just to disable the embedded version and require that the user included the header (or a compatible one) prior to including tinyexr.h. This relies on Miniz keeping a zlib-compatible interface but that's probably a safe assumption.

A key point for me is that I'd prefer not to have to modify tinyexr.h at all so that I can just drop in any updates.

**Comment by syoyo** [comment]
> I don't see that it's necessary to add a new define, it's simpler just to disable the embedded version and require that the user included the header (or a compatible one) prior to including tinyexr.h

I see. Let me give some time to figure out what is the best way to solve the issue with minimal modification.

**Comment by syoyo** [comment]
Do you need miniz specific API for your project, @zigguratvertigo?

If you are ok to use zlib-compatible API, as @john-chapman suggests, there is no modification required anymore and you can include external `miniz.h` as follows.
 
```
#include <miniz/miniz.h> // Use zlib compatible API

#define TINYDNG_USE_MINIZ (0) // Disable embedded miniz code in tinyexr.h
#include "tinyexr.h"
```

**Comment by john-chapman** [comment]
@syoyo One additional problem I noticed: there's a block of `#pragma warning` starting line 4377 which is disabled with `TINYEXR_USE_MINIZ`, but probably shouldn't be.

**Comment by syoyo** [comment]
I see > there's a block of #pragma warning starting line 4377 which is disabled with TINYEXR_USE_MINIZ, but probably shouldn't be.

**Comment by syoyo** [comment]
Fixed wrong pragma warning push/pop pair in this commit: https://github.com/syoyo/tinyexr/commit/13a6b15b31b4f9abe2364f6fe283d3662d700285

**Comment by syoyo** [comment]
Plese reopen the issue if you still get a problem.
