### ISSUE TITLE
Segmentation Fault on 64 bit

### ISSUE THREAD

**Issue by Benjamin-L** [syoyo/tinyexr#5]
When attempting to load EXR images on a 64 bit computer I get a segmentation fault on this line:
```
tinyexr.cc:7039
    (*out_rgba)[4 * i + 3] = exrImage.images[idxA][i];
```

This worked fine on a 32 bit computer so I think that the architecture of the computer might be the problem.

**Comment by syoyo** [comment]
Oops, the problem is malloc size was not enough to store RGBA image. 

Fixed in the above commit.

Thanks for the reporting!
