### ISSUE TITLE
Heap Out-Of-Bounds Memory Access

### ISSUE THREAD

**Issue by Google-Autofuzz** [syoyo/tinyexr#50]
Hello tinyexr team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
tinyexr (tested with revision * master fde4fb5101c72a54f852ee4b9d1de1389691492d).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
* `mkdir project`
* `cp Dockerfile /path/to/project`
* `docker build --no-cache /path/to/project`
* `docker run -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

=================================================================
==10==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000efd3 at pc 0x00000051a784 bp 0x7ffcf83d0690 sp 0x7ffcf83d0688
READ of size 4 at 0x60200000efd3 thread T0
    #0 0x51a783 in tinyexr::ParseEXRHeader(tinyexr::HeaderInfo*, bool*, _EXRVersion const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned char const*, unsigned long) /fuzzing/tinyexr/./tinyexr.h:10176:7
    #1 0x518a9a in ParseEXRHeaderFromMemory /fuzzing/tinyexr/./tinyexr.h:10824:13
    #2 0x5180d5 in ParseEXRHeaderFromFile /fuzzing/tinyexr/./tinyexr.h:12081:10
    #3 0x516e63 in LoadEXR /fuzzing/tinyexr/./tinyexr.h:10695:15
    #4 0x528cdb in main /fuzzing/tinyexr/test_tinyexr.cc:120:13
    #5 0x7fb059a772b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #6 0x41d459 in _start (/fuzzing/tinyexr/test_tinyexr+0x41d459)

0x60200000efd3 is located 2 bytes to the right of 1-byte region [0x60200000efd0,0x60200000efd1)
allocated by thread T0 here:
    #0 0x5049d0 in operator new(unsigned long) (/fuzzing/tinyexr/test_tinyexr+0x5049d0)
    #1 0x539e7b in std::vector<unsigned char, std::allocator<unsigned char> >::_M_fill_insert(__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, unsigned long, unsigned char const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/vector.tcc:491:34
    #2 0x539bff in std::vector<unsigned char, std::allocator<unsigned char> >::resize(unsigned long, unsigned char) /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0/../../../../include/c++/6.3.0/bits/stl_vector.h:717:4
    #3 0x524d6f in tinyexr::ReadAttribute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<unsigned char, std::allocator<unsigned char> >*, unsigned long*, char const*, unsigned long) /fuzzing/tinyexr/./tinyexr.h:7130:9
    #4 0x5190ae in tinyexr::ParseEXRHeader(tinyexr::HeaderInfo*, bool*, _EXRVersion const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned char const*, unsigned long) /fuzzing/tinyexr/./tinyexr.h:10094:10
    #5 0x518a9a in ParseEXRHeaderFromMemory /fuzzing/tinyexr/./tinyexr.h:10824:13
    #6 0x5180d5 in ParseEXRHeaderFromFile /fuzzing/tinyexr/./tinyexr.h:12081:10
    #7 0x516e63 in LoadEXR /fuzzing/tinyexr/./tinyexr.h:10695:15
    #8 0x528cdb in main /fuzzing/tinyexr/test_tinyexr.cc:120:13
    #9 0x7fb059a772b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: heap-buffer-overflow /fuzzing/tinyexr/./tinyexr.h:10176:7 in tinyexr::ParseEXRHeader(tinyexr::HeaderInfo*, bool*, _EXRVersion const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, unsigned char const*, unsigned long)
Shadow bytes around the buggy address:
  0x0c047fff9da0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9db0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9dc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9dd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9de0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c047fff9df0: fa fa fa fa fa fa fa fa fa fa[01]fa fa fa fd fa
  0x0c047fff9e00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9e10: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9e20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9e30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9e40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==10==ABORTING

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team
b/38482728
[artifacts_38482728.zip](https://github.com/syoyo/tinyexr/files/1560302/artifacts_38482728.zip)

**Comment by syoyo** [comment]
Fixed in this commit: https://github.com/syoyo/tinyexr/commit/c80a3683cf92cd4fedb0592829d3c0f4e128c047
