### ISSUE TITLE
What is the recommended way to save an .exr file?

### ISSUE THREAD

**Issue by richardeakin** [syoyo/tinyexr#6]
Hello, and thanks for making this code available, we are evaluating making use of it within the [libcinder](https://github.com/cinder/Cinder) project. I was hoping you could clarify what the recommended way is to write an .exr file, as the usage example doesn't specify how to do this. I was looking at [exrwritetest.cpp](https://github.com/syoyo/tinyexr/blob/master/test/exrwrite/exrwritetest.cpp) which uses `SaveEXR`, but this appears to be [commented out](https://github.com/syoyo/tinyexr/blob/master/tinyexr.h#L97-L98), so is the recommended approach to use `SaveMultiChannelEXRToFile` instead?

Thanks for helping me get started!
Rich

**Comment by syoyo** [comment]
Cool! > `libcinder`

`SaveMultiChannelEXRToFile` or `SaveMultiChannelEXRToMemory` are the recommended way to save RGB(A) EXR.

Please see updated `README.md`

https://github.com/syoyo/tinyexr/commit/4a807ecfd60ca70c4d6e51371898ee263ba828ed

`exrwritetest.cpp` is a bit older so I need to refactor codes...

**Comment by richardeakin** [comment]
Okay, makes perfect sense. Thanks for the example code.
