### ISSUE TITLE
Assert failure in tinyexr::DecompressRle

### ISSUE THREAD

**Issue by Google-Autofuzz** [syoyo/tinyexr#68]
Hello TinyEXR team,

As part of our fuzzing efforts at Google, we have identified an issue affecting
Unicorn (tested with revision master 94d76d230c08b0f729d47179402b9c99cd7e69e2).

To reproduce, we are attaching a Dockerfile which compiles the project with
LLVM, taking advantage of the sanitizers that it offers. More information about
how to use the attached Dockerfile can be found here:
https://docs.docker.com/engine/reference/builder/

TL;DR instructions:
* `mkdir project`
* `cp Dockerfile /path/to/project`
* `docker build --no-cache /path/to/project`
* `docker run -it image_id_from_docker_build`

From another terminal, outside the container:
`docker cp /path/to/attached/reproducer running_container_hostname:/fuzzing/reproducer`
(reference: https://docs.docker.com/engine/reference/commandline/cp/)

And, back inside the container:
`/fuzzing/repro.sh /fuzzing/reproducer`

Alternatively, and depending on the bug, you could use gcc, valgrind or other
instrumentation tools to aid in the investigation. The sanitizer error that we
encountered is here:

fuzzer: ./tinyexr.h:7674: void tinyexr::DecompressRle(unsigned char *, const unsigned long, const unsigned char *, unsigned long): Assertion `ret == static_cast<int>(uncompressed_size)' failed.

We will gladly work with you so you can successfully confirm and reproduce this
issue. Do let us know if you have any feedback surrounding the documentation.

Once you have reproduced the issue, we'd appreciate to learn your expected
timeline for an update to be released. With any fix, please attribute the report
to "Google Autofuzz project".

We are also pleased to inform you that your project is eligible for inclusion to
the OSS-Fuzz project, which can provide additional continuous fuzzing, and
encourage you to investigate integration options.

Don't hesitate to let us know if you have any questions!

Google AutoFuzz Team

[tinyexr-2018012904.zip](https://github.com/syoyo/tinyexr/files/1672174/tinyexr-2018012904.zip)

**Comment by syoyo** [comment]
Please post non-docker reporoducable code and accompanying PR, otherwise I'll reject  such an meaningless issue report.
