### ISSUE TITLE
very high system memory usage when load an .EXR

### ISSUE THREAD

**Issue by RichardGe** [syoyo/tinyexr#69]
Hi, with the joined EXR, the system memory will reach > 10 GB.
it's seems that it's  allocating  512 tiles with each tile :  2048 * 1024.
[fail.zip](https://github.com/syoyo/tinyexr/files/1765083/fail.zip)

**Comment by takahiroharada** [comment]
@syoyo , you can close this as my pr fixes this.

**Comment by syoyo** [comment]
Good! Closed.
