### ISSUE TITLE
deepview example returning error message "ERR: Unsupported version or scanline."

### ISSUE THREAD

**Issue by richardeakin** [syoyo/tinyexr#7]
Just a heads up that this is what I am seeing with a fresh checkout, and running:

```
cd examples/deepview
make
./deepview ../../asakusa.exr
```

printout is: "ERR: Unsupported version or scanline."

**Comment by syoyo** [comment]
Since `asakusa.exr` is not a deep image EXR file, thus this is the expected behaviour.

`transparent.exr` is the deep image EXR file.

**Comment by richardeakin** [comment]
Ah, great, yes that one works here. Thanks for the explanation.
