### ISSUE TITLE
Basic loading of EXR images doesn't seem to work

### ISSUE THREAD

**Issue by ialhashim** [syoyo/tinyexr#71]
It seems only the first row is read correctly. I am attaching the 2x2 image:
[simple_case.zip](https://github.com/syoyo/tinyexr/files/1803775/simple_case.zip)

And here is a simple application that reads the 'exr' file and prints the pixel values:
[main.zip](https://github.com/syoyo/tinyexr/files/1803776/main.zip)

(on Windows + VS 2017)

**Comment by ialhashim** [comment]
I might have solved the bug by adding `data_height++;` at the function `DecodeEXRImage` (line 10711)

**Comment by syoyo** [comment]
> I might have solved the bug by adding data_height++; at the function DecodeEXRImage (line 10711)

**Comment by syoyo** [comment]
Fixed! And added regression test here : https://github.com/syoyo/tinyexr/commit/d3493f82cdbc09fbe87fe977a5718119cbf96bef#diff-81fb99a07700f5a308d94c50b1e9c9c4R748

**Comment by ialhashim** [comment]
Thanks! here is the use case (a basic Python wrapper) https://github.com/ialhashim/PyEXR

**Comment by syoyo** [comment]
Awesome!

Listed PyEXR to README! > https://github.com/syoyo/tinyexr/commit/5d3152b2ba847629a463eb7a42097e2a64b86fef#diff-04c6e90faac2675aa89e2176d2eec7d8R72
