### ISSUE TITLE
deepview segfaults on linux and macos

### ISSUE THREAD

**Issue by apbodnar** [syoyo/tinyexr#72]
Tested with Ubuntu 16.04 and macOS sierra.  Built using the makefile for macos and `g++ -o deepview main.cc trackball.cc ../../tinyexr.cc -lglut -lGL -lGLU` on linux.   The same image file works on windows.

**Comment by syoyo** [comment]
Not all deep images are supported(See `README.md`).
Please attach deep image exr to reproduce an issue.

FYI, at least `transparent.exr` in this tinyexr repo can be read correctly.

**Comment by apbodnar** [comment]
Thanks for responding. I've attached the file i'm testing with.
[output.exr.zip](https://github.com/syoyo/tinyexr/files/1921669/output.exr.zip)

**Comment by syoyo** [comment]
Oops, I have committed debug code. 

After removing it at least no segfault occurs and I can see some visual with given test image: https://github.com/syoyo/tinyexr/commit/1ad2991d9dd076586e67eea9b94211b5e9e71209

**Comment by apbodnar** [comment]
Great.  It works with that change. Thanks!

**Comment by syoyo** [comment]
Good. So close the issue.
