### ISSUE TITLE
Memory leaks in ParseEXRHeaderFromMemory

### ISSUE THREAD

**Issue by ChijinZ** [syoyo/tinyexr#79]
git log

    commit 6fd0c1f7575b9119f287fbe5577b2eff41c71bd5
    Author: Syoyo Fujita <syoyo@lighttransport.com>
    Date:   Thu Jun 7 13:53:40 2018 +0900

I build tinyexr with clang and leak sanitizer. When testcase (see: https://github.com/ChijinZ/security_advisories/blob/master/tinyexr_6fd0c1f/memory_leak) is input into test_tinyexr (command: ./test_tinyexr testcase), sanitizer detected memory leaks in *ParseEXRHeaderFromMemory*.

Leak sanitizer provided information as below:

    ==25951==ERROR: LeakSanitizer: detected memory leaks

    Direct leak of 30 byte(s) in 1 object(s) allocated from:
        #0 0x441968 in strdup /home/ubuntu/llvm/llvm-6.0.0.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:407
        #1 0x53a6a7 in ParseEXRHeaderFromMemory /home/ubuntu/fuzz/tinyexr/tinyexr_6fd0c1f/./tinyexr.h:11101:16
        #2 0x5392cd in ParseEXRHeaderFromFile /home/ubuntu/fuzz/tinyexr/tinyexr_6fd0c1f/./tinyexr.h:12375:10

    SUMMARY: AddressSanitizer: 30 byte(s) leaked in 1 allocation(s)

**Comment by syoyo** [comment]
I know this memory leak. You can contribute PR!

**Comment by syoyo** [comment]
Refactor error messaging and  changed API behavior so that now user must free a buffer of error message on failure.

 https://github.com/syoyo/tinyexr/commit/f79bbf952a39890e7ec6cfb199e285e17fd8aa3b
