### ISSUE TITLE
Assert failure

### ISSUE THREAD

**Issue by ChijinZ** [syoyo/tinyexr#84]
When testcase (see: https://github.com/ChijinZ/security_advisories/blob/master/tinyexr_16aba30/assert_failure) is input into test_tinyexr (command: ./test_tinyexr testcase), a assert-failure problem is triggered in tinyexr.h:9589.

    test_tinyexr: tinyexr.h:9589: bool tinyexr::DecodePixelData(unsigned char**, const int*, const unsigned char*, size_t, int, int, int, int, int, int, int, int, size_t, size_t, const EXRAttribute*, size_t, const EXRChannelInfo*, const std::vector<long unsigned int>&): Assertion `ret' failed.
    Aborted

**Comment by syoyo** [comment]
You can return false and do some error handling if you want to avoid assert failure. PR is appreciated.
