### ISSUE TITLE
Failing to open greyscale images

### ISSUE THREAD

**Issue by Zylann** [syoyo/tinyexr#99]
As found in https://github.com/godotengine/godot/issues/24247, TinyEXR seems to be unable to load the following image, which was made in Gimp in greyscale mode with 16-bit float precision:
[round1.zip](https://github.com/syoyo/tinyexr/files/2661091/round1.zip)
The error is:
```
Load EXR err: R channel not found(code -4)
```

**Comment by syoyo** [comment]
TinyEXR itself supports loading this file(`Y` channel only image).

I recommend to follow this to load EXR image https://github.com/syoyo/tinyexr#loading-singlepart-exr-from-a-file

Anyway, I have added support to load EXR image with only `Y` channels exists into `LoadEXR` function for the convenience : https://github.com/syoyo/tinyexr/commit/5ae30aa326f9efe487529644ccc1ba59aa3a832e
